[2022-06-14 22:20:20,373] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.sample-task scheduled__2022-06-13T22:20:09.801408+00:00 [queued]>
[2022-06-14 22:20:20,402] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.sample-task scheduled__2022-06-13T22:20:09.801408+00:00 [queued]>
[2022-06-14 22:20:20,424] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 22:20:20,425] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-14 22:20:20,426] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 22:20:20,465] {taskinstance.py:1377} INFO - Executing <Task(SenatorsOperator): sample-task> on 2022-06-13 22:20:09.801408+00:00
[2022-06-14 22:20:20,471] {standard_task_runner.py:52} INFO - Started process 7280 to run task
[2022-06-14 22:20:20,475] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'sample-task', 'scheduled__2022-06-13T22:20:09.801408+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmp_324eohr', '--error-file', '/tmp/tmpdu9yebfs']
[2022-06-14 22:20:20,489] {standard_task_runner.py:80} INFO - Job 26: Subtask sample-task
[2022-06-14 22:20:20,573] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.sample-task scheduled__2022-06-13T22:20:09.801408+00:00 [running]> on host c19de67e094a
[2022-06-14 22:20:20,755] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=sample-task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T22:20:09.801408+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-13T22:20:09.801408+00:00
[2022-06-14 22:20:21,816] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/operators/request/senators.py", line 27, in execute
    dfPalamentar.to_csv("../../dags/list_palamentar.csv", sep=";")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '../../dags/list_palamentar.csv'
[2022-06-14 22:20:21,848] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=sample-task, execution_date=20220613T222009, start_date=20220614T222020, end_date=20220614T222021
[2022-06-14 22:20:21,900] {standard_task_runner.py:97} ERROR - Failed to execute job 26 for task sample-task ([Errno 2] No such file or directory: '../../dags/list_palamentar.csv'; 7280)
[2022-06-14 22:20:21,969] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-14 22:20:22,104] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
