[2022-06-14 22:24:22,034] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.sample-task scheduled__2022-06-13T22:24:13.429229+00:00 [queued]>
[2022-06-14 22:24:22,045] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.sample-task scheduled__2022-06-13T22:24:13.429229+00:00 [queued]>
[2022-06-14 22:24:22,046] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 22:24:22,047] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-14 22:24:22,048] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-14 22:24:22,059] {taskinstance.py:1377} INFO - Executing <Task(SenatorsOperator): sample-task> on 2022-06-13 22:24:13.429229+00:00
[2022-06-14 22:24:22,065] {standard_task_runner.py:52} INFO - Started process 7489 to run task
[2022-06-14 22:24:22,068] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'sample-task', 'scheduled__2022-06-13T22:24:13.429229+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmp5ulafeyj', '--error-file', '/tmp/tmpib8uias1']
[2022-06-14 22:24:22,070] {standard_task_runner.py:80} INFO - Job 29: Subtask sample-task
[2022-06-14 22:24:22,147] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.sample-task scheduled__2022-06-13T22:24:13.429229+00:00 [running]> on host c19de67e094a
[2022-06-14 22:24:22,198] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=sample-task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T22:24:13.429229+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-13T22:24:13.429229+00:00
[2022-06-14 22:24:23,109] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/operators/request/senators.py", line 27, in execute
    os.chdir('airflow/dags/operators/request')
FileNotFoundError: [Errno 2] No such file or directory: 'airflow/dags/operators/request'
[2022-06-14 22:24:23,139] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=sample-task, execution_date=20220613T222413, start_date=20220614T222422, end_date=20220614T222423
[2022-06-14 22:24:23,152] {standard_task_runner.py:97} ERROR - Failed to execute job 29 for task sample-task ([Errno 2] No such file or directory: 'airflow/dags/operators/request'; 7489)
[2022-06-14 22:24:23,170] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-14 22:24:23,203] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
